---
# task for dgnest.letsencrypt

- name: Ensure webroot exists
  file:
    path: "{{ letsencrypt_webroot_path }}"
    state: directory
    follow: true
  become: true

- name: Attempt to get the certificate using the webroot authenticator
  command: "{{ letsencrypt_command }} -a webroot --webroot-path {{ letsencrypt_webroot_path }} certonly"
  become: true
  args:
    creates: "/etc/letsencrypt/live/{{ letsencrypt_cert_domains[0] }}"
  when: letsencrypt_authenticator == "webroot"
  ignore_errors: True

- name: Attempt to get the certificate using the standalone authenticator (in case eg the webserver is not running yet)
  command: "{{ letsencrypt_command }} -a standalone auth {{ letsencrypt_standalone_command_args }}"
  become: true
  args:
    creates: "/etc/letsencrypt/live/{{ letsencrypt_cert_domains[0] }}"
