---

# task file for dgnest.letsencrypt

- name: Update package repositories
  become: true
  apt:
    update_cache: True
  become: true
  when: ansible_pkg_mgr == "apt"
  tags:
    - apt
    - update_cache
    - install

- name: Install letsencrypt package dependencies
  package: name={{ item }} state=present
  become: true
  with_items: "{{ _letsencrypt_packages | default([]) }}"
  register: install_letsencrypt_packages
  when: _letsencrypt_packages is defined
  with_items: _letsencrypt_packages
  tags:
    - install
