---

# task file for dgnest.letsencrypt

- name: Update package repositories
  sudo: yes
  apt:
    update_cache: True
  when: ansible_distribution == "Ubuntu"
  tags:
    - apt
    - update_cache

- name: Install letsencrypt package dependencies
  sudo: yes
  apt:

    name: "{{ item }}"

    state: present
  register: install_letsencrypt_package_dependencies
  when: _letsencrypt_package_dependencies is defined
  with_items: _letsencrypt_package_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_letsencrypt_package_dependencies.stdout_lines

- name: Install letsencrypt dependencies
  sudo: yes
  apt:

    name: "{{ item.name }}"

    state: present
  register: install_letsencrypt_dependencies
  when: _letsencrypt_dependencies is defined
  with_items: _letsencrypt_dependencies
  tags:
    - apt
    - dependencies
- debug: var=install_letsencrypt_dependencies.stdout_lines
