---
# environment file for dgnest.letsencrypt

- name: Create files letsencrypt
  become: true
  file:

    path: "{{ item.path }}"
    state: "{{ item.state }}"
    owner: "{{ item.owner }}"

  with_items: _letsencrypt_create_files
  when: _letsencrypt_create_files is defined
