---
# task for dgnest.letsencrypt

- name: Install python depends
  pip:
    virtualenv: "{{ letsencrypt_venv }}"
    virtualenv_site_packages: no
    name: "{{ item }}"
    state: latest
    virtualenv_python: python2
  become: true
  with_items: '{{_letsencrypt_pip_packages}}'
  tags:
    - install
