---
# task for dgnest.letsencrypt

- name: Install packages via pip letsencrypt
  sudo: yes

  pip: name="{{ item.name }}" version="{{ item.version }}"

  when: letsencrypt_pip_dependencies is defined
  with_items: letsencrypt_pip_dependencies
