---
# task for dgnest.letsencrypt

- name: Upgrade pip wheel and setuptools
  pip:
    name: "{{ item }}"
    virtualenv: "{{ letsencrypt_venv }}"
    state: latest
    extra_args: '--upgrade'
  with_items:
    - pip
    - wheel
    - setuptools

- name: Install python depends
  pip:
    virtualenv: "{{ letsencrypt_venv }}"
    virtualenv_site_packages: no
    name: "{{ item }}"
    state: present
    virtualenv_python: python2
  become: true
  with_items: '{{ _letsencrypt_pip_packages | default([]) }}'
  when: _letsencrypt_pip_packages is defined
  tags:
    - install
