---
# task for dgnest.letsencrypt

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items: "{{ _letsencrypt.templates | default({}) }}"
  when: _letsencrypt.templates is defined
